"""Generate M12 submission linkage manifest (JSON + Markdown) from repo sources.

    python scripts/generate_m12_submission_linkage.py --write
    python scripts/generate_m12_submission_linkage.py --check

Reads ``docs/milestones/M12/artifacts/m12_linkage_sources.json`` and enriches it with
notebook release metadata (``m11_notebook_release_manifest.json``), file SHA-256 hashes,
and optional ``git rev-parse HEAD`` for the repo tip.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

_SCRIPTS_DIR = Path(__file__).resolve().parent
_ROOT = _SCRIPTS_DIR.parent

_SOURCES = _ROOT / "docs/milestones/M12/artifacts/m12_linkage_sources.json"
_OUT_JSON = _ROOT / "docs/milestones/M12/artifacts/m12_submission_linkage.json"
_OUT_MD = _ROOT / "docs/milestones/M12/artifacts/m12_submission_linkage.md"
_M11_NB_MANIFEST = _ROOT / "docs/milestones/M11/artifacts/m11_notebook_release_manifest.json"


def _canonical_json(obj: Any) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _file_sha256(path: Path) -> str:
    raw = path.read_bytes()
    if path.suffix.lower() in {".csv", ".json", ".md", ".ipynb"}:
        raw = raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    h = hashlib.sha256()
    h.update(raw)
    return h.hexdigest()


def _repo_tip_sha(root: Path) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            text=True,
            stderr=subprocess.DEVNULL,
        )
        return out.strip() or None
    except (OSError, subprocess.CalledProcessError):
        return None


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def build_linkage_payload(root: Path) -> dict[str, Any]:
    if not _SOURCES.is_file():
        msg = f"Missing linkage sources: {_SOURCES}"
        raise FileNotFoundError(msg)
    sources = _load_json(_SOURCES)

    nb_manifest: dict[str, Any] = {}
    if _M11_NB_MANIFEST.is_file():
        nb_manifest = _load_json(_M11_NB_MANIFEST)

    notebook_release = nb_manifest.get("entries", [])

    file_hashes: dict[str, str] = {}
    for rel in sorted({e.get("notebook_path") for e in notebook_release if e.get("notebook_path")}):
        p = root / rel
        if p.is_file():
            file_hashes[rel] = _file_sha256(p)

    evidence_hashes: dict[str, dict[str, str]] = {}
    ev_block = sources.get("evidence_artifacts") or {}
    for milestone, paths in ev_block.items():
        evidence_hashes[milestone] = {}
        for rel in paths:
            p = root / rel
            if p.is_file():
                evidence_hashes[milestone][rel] = _file_sha256(p)
            else:
                evidence_hashes[milestone][rel] = "MISSING"

    return {
        "schema_version": "m12_submission_linkage_v1",
        "generator": "scripts/generate_m12_submission_linkage.py",
        "sources_file": _relative(root, _SOURCES),
        "sources_file_sha256": _file_sha256(_SOURCES),
        "linkage": sources,
        "m11_notebook_release_manifest_path": _relative(root, _M11_NB_MANIFEST),
        "m11_notebook_release_manifest_sha256": _file_sha256(_M11_NB_MANIFEST)
        if _M11_NB_MANIFEST.is_file()
        else None,
        "notebook_release_entries": notebook_release,
        "notebook_file_sha256": file_hashes,
        "evidence_artifact_sha256": evidence_hashes,
    }


def _render_markdown(payload: dict[str, Any]) -> str:
    lk = payload.get("linkage") or {}
    slug = lk.get("kaggle_benchmark_slug", "")
    pub = lk.get("publication_status", "")
    lines = [
        "# M12 — Submission linkage (generated)",
        "",
        f"**Benchmark version:** `{lk.get('benchmark_version')}`  ",
        f"**Kaggle benchmark slug:** `{slug}`  ",
        f"**Publication status:** `{pub}`  ",
        "",
        "Do not edit this file by hand; regenerate with "
        "`python scripts/generate_m12_submission_linkage.py --write`.",
        "",
        "## Primary vs secondary project links",
        "",
        "- **Primary competition-facing project link (intended):** Kaggle benchmark page "
        f"for `{slug}` once `kaggle_benchmark_url` is set in `m12_linkage_sources.json`.",
        f"- **Secondary implementation / source:** `{lk.get('github_repository_url')}`",
        f"- **Competition hub:** `{lk.get('competition_url')}`",
        "",
        "## External rules / documentation (citations)",
        "",
    ]
    for c in lk.get("external_rules_citations") or []:
        title = c.get("title", "")
        url = c.get("url", "")
        summ = c.get("summary", "")
        lines.append(f"- [{title}]({url}) — {summ}")
    lines.extend(
        [
            "",
            "## Tasks and source notebooks",
            "",
            "| Task | Notebook | Generator | URL | Status |",
            "|------|----------|-----------|-----|--------|",
        ]
    )
    for t in lk.get("tasks") or []:
        lines.append(
            f"| `{t.get('task_name')}` | `{t.get('notebook_path')}` | `{t.get('generator')}` | "
            f"`{t.get('task_url')}` | `{t.get('publication_status')}` |"
        )
    lines.extend(
        [
            "",
            "## Writeup artifacts",
            "",
        ]
    )
    for p in lk.get("writeup_artifact_paths") or []:
        lines.append(f"- `{p}`")
    lines.extend(
        [
            "",
            "## Evidence artifact hashes (committed paths)",
            "",
        ]
    )
    evh = payload.get("evidence_artifact_sha256") or {}
    for ms, hashes in sorted(evh.items()):
        lines.append(f"### {ms}")
        for rel, h in sorted(hashes.items()):
            lines.append(f"- `{rel}` → `{h}`")
        lines.append("")
    lines.extend(
        [
            "## Notebook release manifest (M11)",
            "",
            f"**Path:** `{payload.get('m11_notebook_release_manifest_path')}`  ",
            f"**SHA-256:** `{payload.get('m11_notebook_release_manifest_sha256')}`  ",
            "",
            "### Per-notebook file hashes",
            "",
        ]
    )
    for rel, h in sorted((payload.get("notebook_file_sha256") or {}).items()):
        lines.append(f"- `{rel}` → `{h}`")
    lines.extend(
        [
            "",
            "_Repo tip SHA is intentionally omitted from this generated file so `--check` stays "
            "deterministic in CI; use `git rev-parse HEAD` when an audit record needs the commit._",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--write", action="store_true", help="Write JSON + Markdown artifacts")
    p.add_argument(
        "--check",
        action="store_true",
        help="Verify artifacts match regenerated payload",
    )
    args = p.parse_args(argv)
    root = _ROOT

    if args.write:
        payload = build_linkage_payload(root)
        _OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
        _OUT_JSON.write_text(_canonical_json(payload), encoding="utf-8", newline="\n")
        _OUT_MD.write_text(_render_markdown(payload), encoding="utf-8", newline="\n")
        print(f"Wrote {_OUT_JSON}")
        print(f"Wrote {_OUT_MD}")
        return 0

    if args.check:
        if not _OUT_JSON.is_file():
            print(f"ERROR: missing {_OUT_JSON}", file=sys.stderr)
            return 2
        regen = build_linkage_payload(root)
        existing = _load_json(_OUT_JSON)
        if existing != regen:
            print(
                "ERROR: m12_submission_linkage.json differs from generator.\n"
                "Run: python scripts/generate_m12_submission_linkage.py --write",
                file=sys.stderr,
            )
            return 1
        md_got = _OUT_MD.read_text(encoding="utf-8").replace("\r\n", "\n")
        md_exp = _render_markdown(regen)
        if md_got != md_exp:
            print("ERROR: m12_submission_linkage.md mismatch", file=sys.stderr)
            return 1
        print("OK: M12 submission linkage artifacts match generator")
        return 0

    p.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
